'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Camera, CheckCircle2, Mic, PhoneOff, ShieldCheck } from 'lucide-react'

export default function ConsultaPage() {
  const [conectado, setConectado] = useState(false)
  const [mensagem, setMensagem] = useState('')
  return <main className="app-shell"><div className="mx-auto min-h-screen max-w-[760px] px-5 py-6"><header className="flex items-center justify-between"><Link href="/app" className="font-display text-xl font-extrabold text-[#0b6e63]">Protea</Link><span className="flex items-center gap-2 text-xs font-semibold text-[#78928e]"><ShieldCheck/> Consulta protegida</span></header><section className="mt-8 overflow-hidden rounded-[32px] bg-[#123f3b] p-5 text-white"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-widest text-white/60">Teleconsulta simulada</p><h1 className="mt-2 font-display text-2xl font-extrabold">Dra. Helena Duarte</h1><p className="mt-1 text-sm text-white/70">Endocrinologia · hoje, 18:00</p></div><span className="rounded-full bg-white/10 px-3 py-1 text-xs">{conectado ? 'Conectado' : 'Aguardando'}</span></div><div className="mt-6 flex aspect-video items-center justify-center rounded-2xl bg-[#1a5b54]"><div className="text-center"><div className="mx-auto flex size-16 items-center justify-center rounded-full bg-[#0f9d8a] text-2xl font-bold">HD</div><p className="mt-3 text-sm text-white/70">{conectado ? 'Você e sua profissional estão na sala' : 'A sala será liberada no horário'}</p></div></div><div className="mt-4 flex justify-center gap-3"><button onClick={() => setConectado(!conectado)} className="flex min-h-12 items-center gap-2 rounded-xl bg-[#0f9d8a] px-5 text-sm font-bold">{conectado ? <PhoneOff/> : <Camera/>}{conectado ? 'Sair da sala' : 'Entrar na sala'}</button><button aria-label="Ativar microfone" className="flex size-12 items-center justify-center rounded-xl bg-white/10"><Mic/></button></div></section><section className="mt-4 rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-[#0f9d8a]"><CheckCircle2/><h2 className="font-display font-bold text-[#123f3b]">Histórico compartilhado</h2></div><p className="mt-2 text-sm leading-relaxed text-[#64817d]">A profissional recebeu apenas sintomas e o resumo da Protea, conforme seu consentimento. O acesso pode ser revogado em Privacidade.</p><div className="mt-4 flex gap-2"><input value={mensagem} onChange={(event) => setMensagem(event.target.value)} placeholder="Escreva uma mensagem para a profissional" className="min-h-11 min-w-0 flex-1 rounded-xl border border-[#d9e8e5] px-3 text-sm outline-none focus:border-[#0f9d8a]"/><button onClick={() => setMensagem('Mensagem enviada')} className="rounded-xl bg-[#e1f3ef] px-4 text-sm font-bold text-[#0b6e63]">Enviar</button></div>{mensagem === 'Mensagem enviada' && <p className="mt-2 text-xs font-semibold text-[#0f9d8a]">Mensagem enviada com segurança.</p>}</section><p className="mt-5 text-center text-[11px] text-[#78928e]">Provedor de vídeo com requisitos de segurança: a confirmar.</p></div></main>
}
